DELETE FROM buttonset;
INSERT INTO buttonset (name) VALUES
('Soldiers'),
('Sanctum'),
('Lunch Money'),
('Vampyres'),
('Legend of the Five Rings'),
('BROM'),
('1999'),
('BRAWL'),
('Buttonlords'),
('Studio Foglio'),
('Sailor Moon 1'),
('Freaks'),
('Fantasy'),
('Dork Victory'),
('Sailor Moon 2'),
('Bruno'),
('2000'),
('Sluggy Freelance'),
('Samurai'),
('2001'),
('Diceland');

# Anime Expo 2002
# Balticon 34
# Bar Mitzvah
# Bridge and Tunnel
# Button Brains
# Chicagoland Gamers Conclave
# Everything to Gain
# Fightball
# Gaming Guardians
# Metamorphers
# Nodwick
# Origins 2004
# Renaissance
# SFR
# ShoreCon 2000
# Space Girlz
# SydCon 10
# Yoyodyne


DELETE FROM button;
INSERT INTO button (name, recipe, tourn_legal, set_id) VALUES
('Bunnies',     '(1) (1) (1) (1) (X)',           0, (SELECT id FROM buttonset WHERE name="1999")),
('Lab Rat',     '(2) (2) (2) (2) (X)',           0, (SELECT id FROM buttonset WHERE name="1999")),
('Brigid',      '(8) (8) (X) (X) (X)',           1, (SELECT id FROM buttonset WHERE name="1999")),
('O-Lass',      '(6) (12) (X) (X) (X)',          1, (SELECT id FROM buttonset WHERE name="1999")),
('Zeppo',       '(4) (12) (20) (X)!',            1, (SELECT id FROM buttonset WHERE name="1999")),
('Eiko',        '(4) (6) (6) (12) (X)',          1, (SELECT id FROM buttonset WHERE name="1999")),
('Wu Lan',      '(4) (10) (20) (20) (X)',        1, (SELECT id FROM buttonset WHERE name="1999")),
# ('Buzzing Weasel','(Fudge) (Regular) (Prestige) (Gamer) (Screw)',         1, (SELECT id FROM buttonset WHERE name="1999")),
# ('James Ernest','(pi) (inf) (sqrt(-2)) (X)',       0, (SELECT id FROM buttonset WHERE name="1999")),
('Dirgo',       '(20) (20) (20) (X)',            1, (SELECT id FROM buttonset WHERE name="1999")),
('Flaire',      '(6) (10) (10) (12) (X)',        1, (SELECT id FROM buttonset WHERE name="1999")),
('Poly',        '(4) (6) F(8) (20) (X)',         1, (SELECT id FROM buttonset WHERE name="1999")),
('Adam Spam',   'F(4) F(6) (6) (12) (X)',        1, (SELECT id FROM buttonset WHERE name="1999")),
('Fuzzface',    '(4) (8) (10) c(10) c(12)',      1, (SELECT id FROM buttonset WHERE name="1999")),
# ('Gordo',       unique swing values   '(V) (W) (X) (Y) (Z)',                 0, (SELECT id FROM buttonset WHERE name="2000")),
('Social Class',        '(4|6) (6|8) (8|10) (10|12) (12|20)', 1, (SELECT id FROM buttonset WHERE name="2000")),
('Tirade',              '(6) ^(6) ^(10) (V)!',                0, (SELECT id FROM buttonset WHERE name="2000")),
('Tess',                'n(4) (8) (12) n(20) (X)',            1, (SELECT id FROM buttonset WHERE name="2000")),
# ('Guillermo',  unique         '(6) (10) (20) (X) (Y)',              1, (SELECT id FROM buttonset WHERE name="2000")),
('Ginzu',               '(8) (8) s(12,12) (20) (X)',          1, (SELECT id FROM buttonset WHERE name="2000")),
('Gratch',              '(6) s(8,8) (20) s(20) (X)',          1, (SELECT id FROM buttonset WHERE name="2000")),
('Bush',                '(4) (20) (4|8) (6|12) (6|20)',       1, (SELECT id FROM buttonset WHERE name="2000")),
('Gore',                '(4) (20) (4|8) (6|12) (6|20)',       1, (SELECT id FROM buttonset WHERE name="2000")),
('Cthulhu',             '(4) (20) s(4,8) s(6,12) ps(6,20)',   1, (SELECT id FROM buttonset WHERE name="2000")),
('Nerni',               '(4) (4) (12) (X) (X)',               1, (SELECT id FROM buttonset WHERE name="2000")),
('Yeti',                '(10) (20) (30) (30) (X)',            1, (SELECT id FROM buttonset WHERE name="2000")),
('Me am ORK',           '(8) (8) (8) p(8) (X)',               1, (SELECT id FROM buttonset WHERE name="2000")),
('Sven',                'q(20) q(20) (8|12) (6|12) (4)',      1, (SELECT id FROM buttonset WHERE name="2000")),
('Yseulte',             'p(20) q(10) q(8) (X) (X)',           1, (SELECT id FROM buttonset WHERE name="2000")),
# ('The Flying Squirrel', 's(6) s(12) s(12) s(20)',             1, (SELECT id FROM buttonset WHERE name="2000")),
# ('The Japanese Beetle', '(6) (8) (12) (X)',                   1, (SELECT id FROM buttonset WHERE name="2000")),
('Howling Wolf',        'd(4) (8) (12) (20) d(20)',           1, (SELECT id FROM buttonset WHERE name="2000")),
('White Tiger',         '(6) d(6) (10) (12) d(12)',           1, (SELECT id FROM buttonset WHERE name="2000")),
('Rikachu',             '(1) (1) (1) (1) (Y)',                0, (SELECT id FROM buttonset WHERE name="2000")),
('Nickie',              'z(4) (10) (10) (12) z(12)',          1, (SELECT id FROM buttonset WHERE name="2001")),
('Sonia',               '(6) (6) z(12) (20) (20)',            1, (SELECT id FROM buttonset WHERE name="2001")),
('Tamiya',              '(4) (8) (8) (12) z(20)',             1, (SELECT id FROM buttonset WHERE name="2001")),
('Jorgi',               '(4) (6) (8) (20) p(X)',              1, (SELECT id FROM buttonset WHERE name="2001")),
('Tsusuko',             'f(6) (10) (10) (16) (X)',            1, (SELECT id FROM buttonset WHERE name="2001")),
('The Effster',         's(4) (8) (8) s(12) (X)',             1, (SELECT id FROM buttonset WHERE name="2001")),
('The Fictitious Alan Clark', 's(8) s(8) (3|12) (20) (X)',    1, (SELECT id FROM buttonset WHERE name="2001")),
('Bennett',     '(6) (8) z(20) z(20) (S)',       1, (SELECT id FROM buttonset WHERE name="BRAWL")),
('Chris',       'z(6) z(8) (10) z(12) (S)',      1, (SELECT id FROM buttonset WHERE name="BRAWL")),
('Darwin',      '(4) (6) z(10) (20) (X)',        1, (SELECT id FROM buttonset WHERE name="BRAWL")),
('Hale',        'z(8) (12) (20) (20) (S)',       1, (SELECT id FROM buttonset WHERE name="BRAWL")),
('Morgan',      'z(10) z(12) z(12) z(X)',        1, (SELECT id FROM buttonset WHERE name="BRAWL")),
('Pearl',       '(6) (8) (12) (X) z(X)',         1, (SELECT id FROM buttonset WHERE name="BRAWL")),
('Sydney',      'z(4) z(6) z(8) (X) z(X)',       0, (SELECT id FROM buttonset WHERE name="BRAWL")),
('Coil',        'p(4) (12) p(20) (20) (V)',      1, (SELECT id FROM buttonset WHERE name="BROM")),
('Bane',        'p(2) p(4) (12) (12) (V)',       1, (SELECT id FROM buttonset WHERE name="BROM")),
('Lucky',       '(6) (10) p(12) (20) (X)',       1, (SELECT id FROM buttonset WHERE name="BROM")),
('Shepherd',    '(8) (8) p(16) (20) (X)',        1, (SELECT id FROM buttonset WHERE name="BROM")),
('Peace',       's(10) s(12) s(20) s(X) s(X)',   1, (SELECT id FROM buttonset WHERE name="BROM")),
('Crusher',     '(10) p(20) (20) (20) (X)',      1, (SELECT id FROM buttonset WHERE name="BROM")),
('Grist',       'p(4) (8) (10) (12) (X)',        1, (SELECT id FROM buttonset WHERE name="BROM")),
('Wastenott',   's(4) s(8) s(10) s(20) s(X)',    1, (SELECT id FROM buttonset WHERE name="BROM")),
('Reaver',      '(4) (10) (10) (12) p(X)',       1, (SELECT id FROM buttonset WHERE name="BROM")),
('Jellybean',   'p(20) s(20) (V) (X)',           1, (SELECT id FROM buttonset WHERE name="BROM")),
('Bluff',       'ps(6) ps(12) (16) (20) (X)',    1, (SELECT id FROM buttonset WHERE name="BROM")),
('Strik',       '(8) p(10) s(16) (16) (X)',      1, (SELECT id FROM buttonset WHERE name="BROM")),
# ('Giant',      slow '(20) (20) (20) (20) (20) (20)', 1, (SELECT id FROM buttonset WHERE name="BROM")),
# ('Echo',       deal with Echo vs Echo '(?) (?) (?) (?) (?)',         1, (SELECT id FROM buttonset WHERE name="BROM")),
# ('Bruno',       'B(4) B(8) B(20) B(20) B(X) (special 1, (X) when facing Pappy)',    1, (SELECT id FROM buttonset WHERE name="Bruno")),
# ('Pappy',       '(4) (4) (10) B(20) (X) (special 2, B(X) when facing Bruno)',    1, (SELECT id FROM buttonset WHERE name="Bruno")),
('Synthia',     'B(4) (12) (12) (T) B(T)',       1, (SELECT id FROM buttonset WHERE name="Bruno")),
('The GM',      '(4) (8) (12) (16) B(U)',        1, (SELECT id FROM buttonset WHERE name="Bruno")),
('Arthur',      '(8) (8) (10) (20) (X) +(20)',   1, (SELECT id FROM buttonset WHERE name="Buttonlords")),
('Mordred',     's(6) (10) (10) s(20) s(X) +(4)',1, (SELECT id FROM buttonset WHERE name="Buttonlords")),
('Lancelot',    '(10) (12) (20) (20) (X) +(X)',  1, (SELECT id FROM buttonset WHERE name="Buttonlords")),
('Gawaine',     '(4) (4) (12) (20) (X) +(6)',    1, (SELECT id FROM buttonset WHERE name="Buttonlords")),
('Morgan Le Fay','s(4) (12) s(12) (20) (X) +(12)',1,(SELECT id FROM buttonset WHERE name="Buttonlords")),
('Guenever',    '(6) s(8) (10) (12) (X) +(8)',   1, (SELECT id FROM buttonset WHERE name="Buttonlords")),
('Nimue',       '(4) (6) s(12) (20) (X) +s(10)', 1, (SELECT id FROM buttonset WHERE name="Buttonlords")),
('Merlin',      '(2) (4) s(10) s(20) (X) +s(X)', 1, (SELECT id FROM buttonset WHERE name="Buttonlords")),
('Buck',        'g(8) g(10) (12) (20) (X)',      1, (SELECT id FROM buttonset WHERE name="Diceland")),
('Cass',        '(4) g(4) g(6) (12) (X)',        1, (SELECT id FROM buttonset WHERE name="Diceland")),
('Z-Don',       'g(6) g(8) p(16) (X) (X)',       1, (SELECT id FROM buttonset WHERE name="Diceland")),
('Crysis',      'g(8) (10) (10) (X) (X)',        1, (SELECT id FROM buttonset WHERE name="Diceland")),
('Golo',        'g(10) g(12) g(20) g(X)',        1, (SELECT id FROM buttonset WHERE name="Diceland")),
('Bill',        '(20) (20) (20) (V,V)',          1, (SELECT id FROM buttonset WHERE name="Dork Victory")),
('Carson',      '(4,4) (8) (10) (12) (V)',       1, (SELECT id FROM buttonset WHERE name="Dork Victory")),
('Gilly',       '(6) (8) z(8) (20) (X)?',        1, (SELECT id FROM buttonset WHERE name="Dork Victory")),
('Igor',        '(3) (12) (20) (20) (X)?',       1, (SELECT id FROM buttonset WHERE name="Dork Victory")),
('Ken',         '(8) (10) z(12) (20) (V)?',      1, (SELECT id FROM buttonset WHERE name="Dork Victory")),
('Matt',        'z(8) (10) (10) z(10) (V)?',     1, (SELECT id FROM buttonset WHERE name="Dork Victory")),
('Luce',        '(8) (10) (20) (4|20) (8|20)',   1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Frasquito',   '(4) (6) (8) (12) (2|20)',       1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Lark',        '(6) (20) (2|8) (4|12) (6|10)',  1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Theophilus',  '(8) (10) (12) (10|20) (20|30)', 1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Mischa',      '(10) (12) (12) (4|12) (6|12)',  1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Chang',       '(2|20) (2|20) (4|20) (8|20)',   1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Aldric',      '(8) (8) (4|12) (8|20) (12|20)', 1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Elihu',       '(4|6) (4|8) (6|10) (6|12) (8|20)', 1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Farrell',     '(10) (12) (6|20) (6|20) (8|12)',1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Nikolai',     '(20) (4|10) (4|12) (6|10) (6|20)', 1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Cesare',      '(10) (4|10) (6|10) (10|12) (10|20)', 1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Vincent',     '(30) (30) (30) (6|30)',         1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Nightmare',   '(4) (8) (10) (20) (20)',        1, (SELECT id FROM buttonset WHERE name="Fantasy")),
# ('Socrates',    '(4) (10) (12) (Y)',             1, (SELECT id FROM buttonset WHERE name="Fantasy")),
# ('Dead Guy',    '(0) (0) (0) (0) (0)',           1, (SELECT id FROM buttonset WHERE name="Fantasy")),
('Max',         'p(12) p(12) p(20) p(20) p(30) p(30) p(X) p(X)', 1, (SELECT id FROM buttonset WHERE name="Freaks")),
('Mister Peach','(6) z(8,8) ps(12,12) (V,V)!',   1, (SELECT id FROM buttonset WHERE name="Freaks")),
('Simon',       'q(4) q(6) q(12) q(20) q(X)',    1, (SELECT id FROM buttonset WHERE name="Freaks")),
('Werner',      '(8) (10) (10) (12) pzs(V)!',    1, (SELECT id FROM buttonset WHERE name="Freaks")),
('Crab',        '(8) (10) (12) f(20) f(20)',     1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Crane',       '(4) f(6) f(8) (10) (12)',       1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Dragon',      '(4) (8) f(8) f(12) (20)',       1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Lion',        '(4) f(6) (10) f(20) (20)',      1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Mantis',      '(6) f(8) f(10) (20) (20)',      1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Naga',        'f(6) (8) (8) (8) f(20)',        1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Phoenix',     '(4) (6) f(8) (10) f(20)',       1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Ronin',       '(6) f(6) (8) f(12) (12)',       1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Scorpion',    '(4) (4) f(4) f(12) (20)',       1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Unicorn',     '(4) (4) f(6) f(12) (20)',       1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Mirumoto',    'f(6) (10) f(10) (12) (20)',     1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Kakita',      '(6) f(6) (10) f(12) (20)',      1, (SELECT id FROM buttonset WHERE name="Legend of the Five Rings")),
('Charity',     't(4) (4) (8) (12) (X)',         1, (SELECT id FROM buttonset WHERE name="Lunch Money")),
('Prudence',    '(1) t(4) (6) (12) (X)',         1, (SELECT id FROM buttonset WHERE name="Lunch Money")),
('Hope',        't(1) (2) t(4) (6) (Y)',         1, (SELECT id FROM buttonset WHERE name="Lunch Money")),
('Chastity',    't(6) (6) (10) (10) (X)',        1, (SELECT id FROM buttonset WHERE name="Lunch Money")),
('Faith',       't(2) (6) (10) (12) (Y)',        1, (SELECT id FROM buttonset WHERE name="Lunch Money")),
('Temperance',  't(2) (8) (12) (20) (Y)',        1, (SELECT id FROM buttonset WHERE name="Lunch Money")),
('Patience',    '(2) (2) (8) (12) (X)',          1, (SELECT id FROM buttonset WHERE name="Lunch Money")),
('Sailor Moon',         '(8) (8) (10) (20) r(6) r(10) r(20) r(20)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Queen Beryl',         '(4) (8) (12) (20) r(4) r(12) r(20) r(20)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Sailor Mercury',      '(4) (8) (8) (12) r(4) r(4) r(8) r(10)',         1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Zoycite',             '(4) (10) (10) (10) r(6) r(6) r(8) r(8)',        1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Sailor Mars',         '(4) (6) (10) (20) r(6) r(10) r(10) r(20)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Jedite',              '(6) (6) (12) (12) r(4) r(6) r(6) r(8)',         1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Sailor Jupiter',      '(6) (10) (12) (20) r(6) r(12) r(12) r(20)',     1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Nephlite',            '(4) (6) (12) (12) r(8) r(10) r(10) r(12)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Sailor Venus',        '(4) (6) (10) (12) r(4) r(8) r(8) r(12)',        1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Malachite',           '(8) (12) (20) (20) r(10) r(12) r(12) r(20)',    1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Tuxedo Mask',         '(6) (6) (10) (20) r(4) r(8) r(10) r(12) r(20)', 1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Shadow Warriors',     '(1) (2) `(4) `(6) `(8) `(10) `(12)',            1, (SELECT id FROM buttonset WHERE name="Sailor Moon 1")),
('Luna & Artemis',      '(1) (4) (10) (20) r(2) r(2) r(8) r(8)',         1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Wicked Lady',         '(6) (6) (10) (12) r(4) r(8) r(10) r(20)',       1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Queen Serenity',      '(4) (6) (10) (12) r(6) r(10) r(12) r(20)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Rubeus',              '(4) (4) (12) (12) r(6) r(10) r(20) r(20)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Princess Serena',     '(6) (8) (12) (20) r(4) r(10) r(12) r(20)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Sapphire',            '(6) (10) (12) (12) r(8) r(8) r(10) r(12)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Rini',                '(2) (4) (6) (6) r(4) r(10) r(12) r(12)',        1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Wiseman',             '(20) (20) (20) (20)',                           1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Neo-Queen Serenity',  '(12) (20) (20) r(4) r(6) r(8) r(10) r(12)',     1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Prince Diamond',      '(4) (6) (12) (20) r(8) r(10) r(10) r(20)',      1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('King Endymion',       '(6) (10) (10) (20) r(6) r(10) r(12) r(20)',     1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Emerald',             '(6) (8) (12) (20) r(4) r(6) r(10) r(20)',       1, (SELECT id FROM buttonset WHERE name="Sailor Moon 2")),
('Honzo',       '(10) (12) f(20) (V) (X)',       1, (SELECT id FROM buttonset WHERE name="Samurai")),
('Konami',      '(6) (8) f(10) f(10) (X)',       1, (SELECT id FROM buttonset WHERE name="Samurai")),
('Okaru',       '(4) f(4) (6) (12) (V)',         1, (SELECT id FROM buttonset WHERE name="Samurai")),
('Sadakuro',    'f(4) f(6) f(8) f(10) (12)',     1, (SELECT id FROM buttonset WHERE name="Samurai")),
('Tonase',      '(4) (4) (8) (20) f(X)',         1, (SELECT id FROM buttonset WHERE name="Samurai")),
('Yuranosuke',  '(4) (8) (12) f(12) (X)',        1, (SELECT id FROM buttonset WHERE name="Samurai")),
('Tsusuko',     'f(6) (10) (10) (16) (X)',       1, (SELECT id FROM buttonset WHERE name="Samurai")),
('Dracha',      '(4) (10) (20) (20) (X)',        1, (SELECT id FROM buttonset WHERE name="Sanctum")),
('Ogi',         '(2) (4) (10) (X) (X)',          1, (SELECT id FROM buttonset WHERE name="Sanctum")),
('Fingle',      '(6) (7) (8) (12) (X)',          1, (SELECT id FROM buttonset WHERE name="Sanctum")),
('Ngozi',       '(4) (6) (8) (10) (X)',          1, (SELECT id FROM buttonset WHERE name="Sanctum")),
('Aylee',       '(8) (10|20) (12) (12|20) (20)', 1, (SELECT id FROM buttonset WHERE name="Sluggy Freelance")),
('Bun-Bun',     '(4|10) (4|12) (6|12) (20) (20)',1, (SELECT id FROM buttonset WHERE name="Sluggy Freelance")),
('KiKi',        '(3|20) (4) (8|12) (10) (10|20)',1, (SELECT id FROM buttonset WHERE name="Sluggy Freelance")),
('Riff',        '(4|20) (6) (6|8) (10|12) (20)', 1, (SELECT id FROM buttonset WHERE name="Sluggy Freelance")),
('Torg',        '(6) (6|20) (8) (10|12) (12|20)',1, (SELECT id FROM buttonset WHERE name="Sluggy Freelance")),
('Zoë',         '(4|12) (6|10) (8) (10|20) (12|20)', 1, (SELECT id FROM buttonset WHERE name="Sluggy Freelance")),
('Avis',        '(4) (4) (10) (12) (X)',         1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Hammer',      '(6) (12) (20) (20) (X)',        1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Bauer',       '(8) (10) (12) (20) (X)',        1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Stark',       '(4) (6) (8) (X) (X)',           1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Clare',       '(6) (8) (8) (20) (X)',          1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Kith',        '(6) (8) (12) (12) (X)',         1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Karl',        '(4) (6) (6) (20) (X)',          1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Iago',        '(20) (20) (20) (X)',            1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Niles',       '(6) (10) (10) (12) (X)',        1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Shore',       '(4) (4) (20) (20) (X)',         1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Hannah',      '(8) (10) (10) (10) (X)',        1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Kublai',      '(4) (8) (12) (20) (X)',         1, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Changeling',  '(X) (X) (X) (X) (X)',           0, (SELECT id FROM buttonset WHERE name="Soldiers")),
('Phil',        '(8) (8) (10,10) (20) (X)',      1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Dixie',       '(4) (6) (10) (12,12) (X)',      1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Growf',       '(4,4) (6) (8) (12) (X)',        1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Buck',        '(6,6) (10) (12) (20) (W,W)',    1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
# ('Winslow',     '(30)',                          0, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Agatha',      '(4) (6) (8,8) (20) (X)',        1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Krosp',       '(4) (6,6) (12) (12) (X)',       1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Klaus',       '(4) (10,10) (20) (20) (W)',     1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Von Pinn',    '(4) p(6,6) (10) (20) (W)',      1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Bang',        'p(4,4) (6) (12) (12) (X)',      1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Gil',         '(8) (8) p(8,8) (20) (X)',       1, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('James',       '(4) (8,8) (10,10) (12) (W,W)',  0, (SELECT id FROM buttonset WHERE name="Studio Foglio")),
('Angel',       's(4) (6) s(12) (12) (X)',       1, (SELECT id FROM buttonset WHERE name="Vampyres")),
('Buddy',       's(6) (10) s(20) (20) (X)',      1, (SELECT id FROM buttonset WHERE name="Vampyres")),
('Dunkirk',     '(6) (6) (10) (20) s(X)',        1, (SELECT id FROM buttonset WHERE name="Vampyres")),
('Starchylde',  's(6) (8) s(10) (12) (X)',       1, (SELECT id FROM buttonset WHERE name="Vampyres")),
('McGinty',     '(4) s(10) (12) (12) (X)',       1, (SELECT id FROM buttonset WHERE name="Vampyres")),
('Tiffany',     '(4) s(8) (8) (10) s(X)',        1, (SELECT id FROM buttonset WHERE name="Vampyres"));
