FROM --platform=linux/amd64 ubuntu:24.04
RUN mkdir /buttonmen
WORKDIR /buttonmen
COPY . .

# Make sure log dir exists
RUN mkdir -p build/logs

# Bootstrap puppet
RUN bash ./deploy/vagrant/bootstrap.sh

# Run puppet
RUN bash ./deploy/vagrant/run_puppet.sh stats_init.pp

# The puppet infrastructure for stats creates this directory
WORKDIR /opt/stats

# Set runtime interface client as default command for the container runtime
ENTRYPOINT [ "/opt/venv/lambda_ic/bin/python", "-m", "awslambdaric" ]
# Pass the name of the function handler as an argument to the runtime
CMD [ "lambda_function.handler" ]
