#!/usr/bin/env python3
# GAME_INFO
# Example script which prints player and opponent information about
# an existing game

import argparse
import sys
sys.path.append("..")
from api_client import bmutils

# implicitly parses sys.argv
def parse_args():
  parser = argparse.ArgumentParser()
  parser.add_argument(
    "-c", "--config",
    help="config file containing site parameters",
    type=str, default=".bmrc"
  )
  parser.add_argument(
    "-s", "--site",
    help="buttonmen site to access",
    type=str, default="www"
  )
  parser.add_argument("gameid")
  return parser.parse_args()


def print_table(tabledata):
  colmax = []
  for i in range(len(tabledata[0])):
    colmax.append(max([len(row[i]) for row in tabledata]))
  for row in tabledata:
    rowstr = ''
    for i in range(len(row)):
      rowstr += row[i]
      for j in range(len(row[i]), colmax[i] + 1):
        rowstr += ' '
    rowstr.strip()
    print(rowstr)


########################################################################
args = parse_args()
b = bmutils.BMClientParser(args.config, args.site)
if not b.verify_login():
  print("Could not login")
  sys.exit(1)

gamedata = b.wrap_load_game_data(args.gameid)
tabledata = []
for player in ['player', 'opponent']:
  tabledata.append(
    [gamedata[player]['playerName'] + ':',
     gamedata[player]['button']['name'] + ':',
     gamedata[player]['button']['recipe'],
     ]
  )
print_table(tabledata)
