UPDATE button SET flavor_text="Rikachu is a bootleg Button Man created at Origins. He's a Pokedog - from the Pokeman ad opposite the Tess page." WHERE name="Rikachu";
UPDATE button SET flavor_text="ConMan plays games at conventions until (and sometimes past) dawn, drinks coffee like it's water, and likes to beat people up." WHERE name="ConMan";
UPDATE button SET flavor_text="The Cheese Weasel is a clever and cunning rodent, bent on quiet world domination. He likes cheese (duh!), any opportunity for eating cheese, stealing cheese...and beating people up if they attempt to come between him and his cheese." WHERE name="Cheese Weasel";
UPDATE button SET flavor_text="Bennett is a big strong boy who loves to take his time. He enjoys math, videotapes, and beating people up." WHERE name="Bennett";
UPDATE button SET flavor_text="Chris knows what she likes and she knows how to get it. She likes chemistry, going to the park, and beating people up." WHERE name="Chris";
UPDATE button SET flavor_text="Darwin is young entrepreneur who enjoys politics, French, and beating people up." WHERE name="Darwin";
UPDATE button SET flavor_text="Hale is a considerate fellow and excels in every class. He is never too busy to stop and beat people up." WHERE name="Hale";
UPDATE button SET flavor_text="Morgan knows the rules. She never does anything without a reason, and she loves to beat people up." WHERE name="Morgan";
UPDATE button SET flavor_text="Pearl can lift almost anyone over her head. She likes sports, theater, and beating people up." WHERE name="Pearl";
UPDATE button SET flavor_text="Agent Orange is the first piece of citrus to ever pursue a career in international espionage. He is licensed not only to kill, but also to play ping-pong and beat people up." WHERE name="Agent Orange";
UPDATE button SET flavor_text="This warrior deity of the ancient Aztec religion enjoys playing ping-pong, being worshipped, and beating people up." WHERE name="Huitzilopochtli";
UPDATE button SET flavor_text="Lisa is a friend of the programmers who is easily talked into appearing in their games. She likes her stuffed Cthulhu doll, heavy metal, fuzzy animals, game shows, and beating people up." WHERE name="Lisa";
UPDATE button SET flavor_text="Once one of the most feared of all wizard duelists, this evil magic user now spends most of his time beating people up." WHERE name="Nethershadow";
UPDATE button SET flavor_text="Phuong is another friend of the programmers. She enjoys dancing, appearing on game shows, and practicing Tae Kwon Do so that she may beat people up." WHERE name="Phuong";
UPDATE button SET flavor_text="Uncle Scratchy runs a flea-racing track. Tired of being stepped on, he has gotten quite good at beating people up." WHERE name="Uncle Scratchy";
UPDATE button SET flavor_text="Bane needlessly worries about things he can never change. He likes cowboys, empty paint cans, and beating people up." WHERE name="Bane";
UPDATE button SET flavor_text="Bluff can not be described by a flippant sound bite. She likes Crusher, bobsled racing, and beating people up." WHERE name="Bluff";
UPDATE button SET flavor_text="Coil can say the alphabet backwards and sometimes does it without noticing. She likes to be told things she already knows, and she likes to beat people up." WHERE name="Coil";
UPDATE button SET flavor_text="Crusher is a mean-spirited bruiser with a heart of stone. He likes ikebana, enforcing the whims of callous superiors, and beating people up." WHERE name="Crusher";
UPDATE button SET flavor_text="Grist is an avid student of Sun Tzu who can move objects with his arms and legs. He likes fast cars, manicures, and beating people up." WHERE name="Grist";
UPDATE button SET flavor_text="Jellybean is a prominent patent attorney who can think with his spines. He likes collie-spaniel crosses, red ink, and beating people up." WHERE name="Jellybean";
UPDATE button SET flavor_text="Lucky's father was murdered by an inconsiderate house guest. She likes road movies, vengeance, and beating people up." WHERE name="Lucky";
UPDATE button SET flavor_text="Peace lives in exile on the island of St Helena, where she enjoys swing dance, solitaire, and beating people up." WHERE name="Peace";
UPDATE button SET flavor_text="Reaver takes unparalleled pleasure in bringing joy to her fellow beings. She enjoys surprise gift giving, platonic love, and beating people up." WHERE name="Reaver";
UPDATE button SET flavor_text="Shepherd has made ignorance of obvious things his lifelong ambition. He likes spoons, forgetting how to do stuff, and beating people up." WHERE name="Shepherd";
UPDATE button SET flavor_text="Strik becomes more accustomed to his new lifestyle with each passing day. He likes quiet walks in the moonlight, bashing things with his head, and beating people up." WHERE name="Strik";
UPDATE button SET flavor_text="Wastenott is dead, dead, dead, dead. He likes getting out once in a while, talking to old friends and beating people up." WHERE name="Wastenott";
UPDATE button SET flavor_text="Al-Khwarizmi wrote an amazing book about solving everyday problems in life and business with mathematics. Our word \"algebra\" came from the title of his book, and the term \"algorithm\" is from a Latin translation of his name." WHERE name="Al-Khwarizmi";
UPDATE button SET flavor_text="Best known for his Theory of Numbers, Carl Friedrich Gauss startled his grade school teacher by deducing that the sum of the integers from 1 to 100 was really the sum of 50 pairs of integers which all add to 101." WHERE name="Carl Friedrich Gauss";
UPDATE button SET flavor_text="Before becoming the Akamai Professor of Internet Mathematics at UC San Diego, Dr. Fan Chung Graham directed math research labs at Bellcore. She and her husband Ron developed semi-random routing theories that keep the Internet running." WHERE name="Fan Chung Graham";
UPDATE button SET flavor_text="Leonard Eugene Dickson loved pure mathematics. He wrote 267 research papers and 18 books, including the three volume \"History of the Theory of Numbers.\" His favorite quote: \"Thank God that number theory is unsullied by any applications.\"" WHERE name="Leonard Eugene Dickson";
UPDATE button SET flavor_text="One of the best known and most respected mathematicians of the 20th century, Paul Erdos (air-dish) wrote or co-authored 1,475 papers. As he put it, \"A mathematician is a machine for turning coffee into theorems.\"" WHERE name="Paul Erdos";
UPDATE button SET flavor_text="Pythagoras and his team in Italy, called the mathematikoi, developed cool triangle theorems, described the five regular solids, and thought that numbers had personal characteristics like male, female, beautiful, and ugly." WHERE name="Pythagoras";
UPDATE button SET flavor_text="Known informally as \"The Mathemagician,\" Dr. Ron Graham was Chief Scientist at AT&T Labs. He's treasurer of the National Academy of Sciences, and also the ex-president of the International Jugglers Association." WHERE name="Ron Graham";
UPDATE button SET flavor_text="Theano worked alongside her husband, Pythagoras, writing about mathematics, physics, medicine, and child psychology. She's best known for her work on the \"Golden Mean\" and the \"Golden Rectangle.\"" WHERE name="Theano";
UPDATE button SET flavor_text="Tirade is a sentient broccoli. He is a master of time, space and dimension, and has 50 dollars to spend on candy and gum. He also likes to beat people up." WHERE name="Tirade";
UPDATE button SET flavor_text="The king's loyal nephew, he fights with the strength of three men." WHERE name="Gawaine";
UPDATE button SET flavor_text="The Queen of the Court of Love, torn between her husband and her lover." WHERE name="Guenever";
UPDATE button SET flavor_text="King of the Britons, the embodiment of Glory and Honor, and betrayed husband." WHERE name="King Arthur";
UPDATE button SET flavor_text="The best knight in the world, torn between his love for the queen and duty to his king." WHERE name="Lancelot";
UPDATE button SET flavor_text="The great magician who advises the king, but who always has his own agenda." WHERE name="Merlin";
UPDATE button SET flavor_text="The king's bastard son, he has had villainy thrust upon him and revels in it." WHERE name="Mordred";
UPDATE button SET flavor_text="The dark enchantress who beguiles all with mysterious faerie magic." WHERE name="Morgan Le Fay";
UPDATE button SET flavor_text="The Lady of the Lake, she holds the powers of Excalibur and Avalon." WHERE name="Nimue";
UPDATE button SET flavor_text="Bill sells \"items\" and \"objects\" at a game store of which he is the proprietor. His many powers include \"discounting\" and \"print advertising\" and he likes to beat people up. (dressed as Iago)" WHERE name="Bill";
UPDATE button SET flavor_text="Carson is a muskrat whose secret origins are steeped in mystery. He enjoys mopping the floor all day, and he likes to beat people up. (dressed as Kublai)" WHERE name="Carson";
UPDATE button SET flavor_text="Gilly is a perky goth who likes to play games. She enjoys just about everything, just about everything else, and beating people up. (dressed as Clare)" WHERE name="Gilly";
UPDATE button SET flavor_text="Igor is a vicious, sweaty man with a garbage can on his head. He likes long walks in the park, red rhubarb jelly and beating people up. (dressed as Hammer)" WHERE name="Igor";
UPDATE button SET flavor_text="Ken is a hard-riding hobbyist with a heart of gold. He likes frivolity, jumping up and down, running with his tongue hanging out, and beating people up. (dressed as Bauer)" WHERE name="Ken";
UPDATE button SET flavor_text="Matt is as loveable as the day is long. Just look at that cute widdow nose. He likes role-playing, the unexpected, and beating people up. (dressed as Hannah)" WHERE name="Matt";
UPDATE button SET flavor_text="Sven is a Trow (troll) who likes to trade recipes with the other queens at the leather bar, swap housekeeping tips with his neighbors, prune roses, and beat people up." WHERE name="Sven";
UPDATE button SET flavor_text="Yseulte is a Fuah (bad water faery) who lives by the Maine Avenue fish market. She likes to party with the Grrls, ride vintage Harleys, smear women's makeup, collect scallop shells, and beat people up." WHERE name="Yseulte";
UPDATE button SET flavor_text="Aldric can belch the anthem of his home town and once drank an entire tankard of beer. He likes damsels, horses, and beating people up." WHERE name="Aldric";
UPDATE button SET flavor_text="Cesare is the banished heir to the throne of a large kingdom. He likes plotting revenge, procrastinating, and beating people up." WHERE name="Cesare";
UPDATE button SET flavor_text="Chang is far less intelligent than most people think he is. He likes long naps, pieces of string, and beating people up." WHERE name="Chang";
UPDATE button SET flavor_text="Elihu senses danger at all times, which makes him tense and irritable. His mind is filled with trivial detail, and he loves to beat people up." WHERE name="Elihu";
UPDATE button SET flavor_text="Farrell spends his weekends by the seaside, watching re-runs and knitting sweaters. But during the week, he likes to beat people up." WHERE name="Farrell";
UPDATE button SET flavor_text="Frasquito is a very short person and the self-proclaimed inventor of lye. He likes fruit trees and oysters, and he likes to beat people up." WHERE name="Frasquito";
UPDATE button SET flavor_text="Lark is a triple Mud Baron on the Planet of the Bird People. He likes waffling, collecting shiny objects, and beating people up." WHERE name="Lark";
UPDATE button SET flavor_text="Luce is a healer and a clever prestidigitator. She can keep children amused for hours using only a pencil, and she likes to beat people up." WHERE name="Luce";
UPDATE button SET flavor_text="Mischa is a tracker whose well-honed nature skills often lead her to the mall. She likes culottes, vegetarian pizza, and beating people up." WHERE name="Mischa";
UPDATE button SET flavor_text="Nikolai eat cow, Nikolai smash house with club. Nikolai hate loud noise. Nikolai love beat people up." WHERE name="Nikolai";
UPDATE button SET flavor_text="Theophilus is a one-eyed giant who knows the future. He is sometimes morose, often melancholy, and always beating people up." WHERE name="Theophilus";
UPDATE button SET flavor_text="Vincent has the cunning of a fox and the table manners of a six-year old boy. He likes tofu, library paste, and beating people up." WHERE name="Vincent";
UPDATE button SET flavor_text="What is love? Only the guy with the big green brain in his hand knows for sure." WHERE name="Max";
UPDATE button SET flavor_text="Mister Peach teaches old ladies how to dance. He is also creepy." WHERE name="Mister Peach";
UPDATE button SET flavor_text="The Doctor is in." WHERE name="Simon";
UPDATE button SET flavor_text="Werner lives underwater and is a crustacean with a helmet. Understandably, people do not trust him." WHERE name="Werner";
UPDATE button SET flavor_text="Dream Wyrm is a dragon (duh!). His hobbies include terrorizing, arson, and trying to defeat the Gaming Guardians." WHERE name="Dream Wyrm";
UPDATE button SET flavor_text="EDG is the 'second in command'. His hobbies include punching people he doesn't like where it hurts, insulting Graveyard Greg, and guarding the gaming systems." WHERE name="EDG";
UPDATE button SET flavor_text="Graveyard Greg is a Gaming Geek. His hobbies include collecting games, playing games, and guarding the gaming systems." WHERE name="Graveyard Greg";
UPDATE button SET flavor_text="Memento-Mori is an evil goth. His hobbies include not playing games, designing unplayable game systems, and trying to defeat the Gaming Guardians." WHERE name="Memento-Mori";
UPDATE button SET flavor_text="Radical is a deus ex machina. Her hobbies include reading, 80s trivia, and guarding the gaming systems." WHERE name="Radical";
UPDATE button SET flavor_text="Randarch is the self-proclaimed 'Savior of the Gaming Industry'. His hobbies include washing his hair, bossing people around, and letting other people guard the gaming systems." WHERE name="Randarch";
UPDATE button SET flavor_text="Scarlet Jester is evil incarnate. His hobbies include destroying gaming systems, manipulating events in his favor, and trying to annihilate the Gaming Guardians." WHERE name="Scarlet Jester";
UPDATE button SET flavor_text="Shane Hensley is the most evil game designer in existence. His hobbies include making alternate history RPGs, tricking people into thinking he's a nice guy, and trying to defeat the Gaming Guardians." WHERE name="Shane Hensley";
UPDATE button SET flavor_text="The Flying Squirrel has the proportionate strength, speed, and cheek space of a North American gray squirrel. He likes breaking the law, cavorting with squirrels, hibernating all winter, and beating people up." WHERE name="The Flying Squirrel";
UPDATE button SET flavor_text="The Japanese Beetle fights for truth, justice, and the American way - as long as it doesn't get in the way of his quest for fame and fortune. He likes tall blondes, sexy communists, and beating people up." WHERE name="The Japanese Beetle";
UPDATE button SET flavor_text="Charity wants to be a social worker when she grows up. When not making grouchy faces, she likes to beat people up." WHERE name="Charity";
UPDATE button SET flavor_text="Chastity wants to be an out-of-work actor when she grows up. She likes her ballet lessons and beating people up." WHERE name="Chastity";
UPDATE button SET flavor_text="Faith wants to be an eschatologist when she grows up. She likes to watch violent cartoons and beat people up." WHERE name="Faith";
UPDATE button SET flavor_text="Hope wants to be a navy seal when she grows up. Besides eating her broccoli, she likes to beat people up." WHERE name="Hope";
UPDATE button SET flavor_text="Prudence wants to be an entomologist when she grows up. She likes chloroforming butterflies and beating people up." WHERE name="Prudence";
UPDATE button SET flavor_text="Temperance wants to be a postal worker when she grows up. She likes small defenseless animals and beating people up." WHERE name="Temperance";
UPDATE button SET flavor_text="Spells and mystic zaps are what Artax does best. His two best words of power are Abracadabra and beatpeopleup." WHERE name="Artax";
UPDATE button SET flavor_text="Nodwick is a henchman extraordinaire! He can pull his weight and everyone else's while getting beaten up." WHERE name="Nodwick";
UPDATE button SET flavor_text="Divine might and duct tape let Piffany put Nodwick back together as she helps beat naughty people up." WHERE name="Piffany";
UPDATE button SET flavor_text="Yeagar is a warrior of renown. He likes ale kegs and using henchmen as catapult ammunition to beat people up." WHERE name="Yeagar";
UPDATE button SET flavor_text="A twisted scientist and practitioner of Pre-Colombian Neurosurgery, the good Doctor would love to beat people up, but his plans never come out as planned." WHERE name="Dr. Speculo";
UPDATE button SET flavor_text="Guillermo is a deadly, cowardly, left-handed swordsman who hates to beat people up." WHERE name="Guillermo";
UPDATE button SET flavor_text="You ask for war, he says \"Desist.\" / Contrarian, he will resist. / Instead of peace, a paci-fist!" WHERE name="Harry Pudding";
UPDATE button SET flavor_text="A naughty tavern wench. Not a big believer in outright force, she would much prefer to beat you up when you are not looking." WHERE name="Lascivia";
UPDATE button SET flavor_text="He'll make you laugh, he'll make you cry. He'll make you kiss your teeth goodbye." WHERE name="MothMan";
UPDATE button SET flavor_text="Jedite is the first Negaverse General, who was sent to the Earth to harvest energy from humans. Jedite likes taking advantage of gullible humans, wearing cool disguises, and trying to take over the world." WHERE name="Jedite";
UPDATE button SET flavor_text="Malachite is the fourth negaverse General, who was sent to Earth to reveal Sailor Moon's identity. Malachite likes taunting the Scouts, arguing with Prince Darien, and trying to take over the world." WHERE name="Malachite";
UPDATE button SET flavor_text="Nephlite is the second Negaverse General, who was sent to Earth to locate the Imperium Silver Crystal. Nephlite likes communicating with the stars, driving fast cars, and trying to take over the world." WHERE name="Nephlite";
UPDATE button SET flavor_text="Queen Beryl is the vicious ruler of the Negaverse, and the loyal servant of the Negaforce. Beryl likes controlling her monster servants, seeking revenge on her enemies, and trying to take over the world." WHERE name="Queen Beryl";
UPDATE button SET flavor_text="Lita is the reincarnation of the Princess of Jupiter, who transforms into the Energetic Fighter, Sailor Jupiter. Sailor Jupiter likes cooking, brawling, chasing boys, and saving the world from the Negaverse." WHERE name="Sailor Jupiter";
UPDATE button SET flavor_text="Raye is the reincarnation of the Princess of Mars, who transforms into the Passionate Fighter, Sailor Mars. Sailor Mars likes shopping, telling fortunes, reading comics, and saving the world from the Negaverse." WHERE name="Sailor Mars";
UPDATE button SET flavor_text="Amy is the reincarnation of the Princess of Mercury, who transforms into the Brilliant Fighter Sailor Mercury. Sailor Mercury likes reading, computers, playing chess, and saving the world from the Negaverse." WHERE name="Sailor Mercury";
UPDATE button SET flavor_text="Serena is the reincarnation of Princess of the Moon, who transforms into the Justice Fighter, Sailor Moon. Sailor Moon likes eating, shopping, playing video games, and saving the world from the Negaverse." WHERE name="Sailor Moon";
UPDATE button SET flavor_text="Mina is the reincarnation of the Princess of Venus, who transforms into the Dynamic Fighter Sailor Venus. Sailor Venus likes shopping, acting, chasing movie stars, and saving the world from the Negaverse." WHERE name="Sailor Venus";
UPDATE button SET flavor_text="The Seven Shadow Warriors are powerful Negaverse monsters, who were all trapped inside Rainbow Crystals. They like fighting, breaking things, being mean, and trying to take over the world." WHERE name="Shadow Warriors";
UPDATE button SET flavor_text="Darien is the reincarnation of the Prince of Earth, who transforms into the Dashing Hero, Tuxedo Mask. Tuxedo Mask likes jogging, reading, studying science, and saving the world from the Negaverse." WHERE name="Tuxedo Mask";
UPDATE button SET flavor_text="Zoycite is the third Negaverse General, who was sent to Earth to collect the seven Rainbow Crystals. Zoycite likes spoiling Nephlite's plans, hugging Malachite, and trying to take over the world." WHERE name="Zoycite";
UPDATE button SET flavor_text="Emerald is the most sinister, mean-spirited, and nasty member of the dark Moon family. Emerald likes being close to those with great power, mocking Rubeus's constant failures, and trying to destroy the universe." WHERE name="Emerald";
UPDATE button SET flavor_text="King Endymion is the future version of Prince Darien and Tuxedo Mask, combined into one man. King Endymion likes invading his own dreams, making holographic projections of himself, and saving the universe from destruction." WHERE name="King Endymion";
UPDATE button SET flavor_text="Luna and Artemis are feline guardians and companions of the Sailor Scouts. They both like working with computers, guiding the Champions of Justice to do what is right, and saving the universe from destruction." WHERE name="Luna & Artemis";
UPDATE button SET flavor_text="Neo-Queen Serenity is the powerful ruler of Crystal Tokyo and the adult form of Sailor Moon. Neo-Queen Serenity likes playing with her daughter, going on walks with her husband, and saving the universe from destruction." WHERE name="Neo-Queen Serenity";
UPDATE button SET flavor_text="Prince Diamond is a passionate man who is the leader of the royal family from the Dark Moon, Nemesis. Prince Diamond likes kidnapping Sailor Moon, being close to his brother Sapphire, and trying to destroy the universe" WHERE name="Prince Diamond";
UPDATE button SET flavor_text="Princess Serena is the alter ego of Sailor Moon who was first born on the Moon during the Silver Millennium. Princess Serena likes dancing with Prince Darien, blasting enemies with her wand, and saving the universe from destruction." WHERE name="Princess Serena";
UPDATE button SET flavor_text="Queen Serenity is the kind and gentle ruler that held court during the Silver Millennium one thousand years ago. Queen Serenity likes beautiful dresses, capturing Shadow Warriors and saving the universe from destruction." WHERE name="Queen Serenity";
UPDATE button SET flavor_text="Rini is a saucy, young, pink-haired child who will someday be the Queen of the Universe. Rini likes eating ice-cream and other goodies, playing with her mommy's shiny crystals, and saving the universe from destruction." WHERE name="Rini";
UPDATE button SET flavor_text="Rubeus travelled one thousand years into the past on his spaceship to present-day Tokyo to capture young Rini. Rubeus likes flirting with the Four Sisters, riding around in his spaceship, and trying to destroy the universe." WHERE name="Rubeus";
UPDATE button SET flavor_text="Sapphire is Prince Diamond's handsome young brother but he was destroyed by Wiseman. Sapphire likes spying on his enemies, standing up for what he believes is right, and trying to destroy the universe." WHERE name="Sapphire";
UPDATE button SET flavor_text="Wicked Lady is an artificial adult form of young Rini, who was twisted and manipulated by Wiseman. Wicked Lady likes hanging out with Prince Diamond, laughing maniacally, and trying to destroy the universe." WHERE name="Wicked Lady";
UPDATE button SET flavor_text="Wiseman is a cloaked frightening being of pure evil that refers to himself in the third person as the \"Doom Phantom\". Wiseman likes floating in the air, making cryptic comments, and trying to destroy the universe." WHERE name="Wiseman";
UPDATE button SET flavor_text="Honzo is a traveling stick salesman with a funnel on his head. He relishes the simplicity of life on the road, and he likes to beat people up." WHERE name="Honzo";
UPDATE button SET flavor_text="Konami is a funny little girl with nothing to say. She likes to stick people with her knife, and she likes to beat people up." WHERE name="Konami";
UPDATE button SET flavor_text="Okaru is fascinated by candy dispensers, and is a world champion on the mechanical bull. She always thinks that she is being followed, and she likes to beat people up." WHERE name="Okaru";
UPDATE button SET flavor_text="Sadakuro owns nothing but a good book and the deadliest fighting tools. He likes long walks in the dark, remaining perfectly still, and beating people up." WHERE name="Sadakuro";
UPDATE button SET flavor_text="Tonase picks a fight with everyone she meets. She is opinionated and naive, she adores small dogs and furniture, and she likes to beat people up." WHERE name="Tonase";
UPDATE button SET flavor_text="Yuranosuke is a fierce warrior who takes nothing for granted. His highest aspiration is to serve the forces of good, and he likes to beat people up." WHERE name="Yuranosuke";
UPDATE button SET flavor_text="Aylee thinks she looks like a pretty flower. She attended Cannibals Anonymous, and she likes to eat people up." WHERE name="Aylee";
UPDATE button SET flavor_text="Bun-Bun isn't your typical mini-lop rabbit. He hates telemarketers with a passion and frequently beats people up." WHERE name="Bun-Bun";
UPDATE button SET flavor_text="Kiki is the friendliest ferret around. She loves lights, and games, and candy, and never means to beat people up." WHERE name="Kiki";
UPDATE button SET flavor_text="Riff is a freelance inventor whose desire to build nifty toys is exceeded only by his joy in building big guns (which sometimes beat people up)." WHERE name="Riff";
UPDATE button SET flavor_text="Torg is a freelance webpage designer. He makes occasional trips to alternate dimensions or past history, where he sometimes beats people up." WHERE name="Torg";
UPDATE button SET flavor_text="Zoe is a college co-ed, but spends most of her time trying to survive her friends' adventures. Luckily, Zoe can take care of herself and beat people up." WHERE name="Zoe";
UPDATE button SET flavor_text="Avis is an expert chainsaw dueler and ice sculptor, and she likes to beat people up." WHERE name="Avis";
UPDATE button SET flavor_text="Bauer is an enthusiastic supporter of global human rights and a first-class sushi chef. And he likes to beat people up." WHERE name="Bauer";
UPDATE button SET flavor_text="Clare is an international spelling and thumb wrestling champion. She enjoys hiking, fishing, and beating people up." WHERE name="Clare";
UPDATE button SET flavor_text="Hammer is a vicious, sweaty man with a garbage can on his head, and he likes to beat people up." WHERE name="Hammer";
UPDATE button SET flavor_text="Hannah clings to a deep and abiding faith in the fundamental goodness of all human beings, and she likes to beat people up." WHERE name="Hannah";
UPDATE button SET flavor_text="Iago is a sorcerer with mystic powers and is available for bar mitzvahs. He also likes to beat people up." WHERE name="Iago";
UPDATE button SET flavor_text="Karl is a world champion kickboxer and a pathological liar. He likes playing drums, and beating people up." WHERE name="Karl";
UPDATE button SET flavor_text="Kith enjoys travel and nature photography. She binds books in her spare time, and she likes to beat people up." WHERE name="Kith";
UPDATE button SET flavor_text="Kublai is an embittered fast-food worker whose time is never his own. He likes malts, orangutans, and beating people up." WHERE name="Kublai";
UPDATE button SET flavor_text="Niles is a three-time winner of the secret Tijuana kitchen utensils freestyle, and he likes to beat people up." WHERE name="Niles";
UPDATE button SET flavor_text="Shore is a stay-at-home dad who likes long walks in the park, etymology, and beating people up." WHERE name="Shore";
UPDATE button SET flavor_text="Stark once thought she was a train for three days, and she likes to beat people up." WHERE name="Stark";
UPDATE button SET flavor_text="Agatha Heterodyne is a fledgling mad scientist. She means well, but tends to blow things up." WHERE name="Agatha";
UPDATE button SET flavor_text="Bangladesh Dupree likes to beat people up." WHERE name="Bang";
UPDATE button SET flavor_text="Brigid the witch is in tune with the ancient eldritch mysteries. She helps people with het spells and potions and if they laugh at her hat, she beats them up." WHERE name="Brigid";
UPDATE button SET flavor_text="Buck Godot is a zap-gun for hire on New Hong Kong, the planet where the only law is that there is no law. He loves this game." WHERE name="Buck Godot";
UPDATE button SET flavor_text="Gil is home from school and learning to run the family business - world domination." WHERE name="Gil";
UPDATE button SET flavor_text="Klaus likes to find out what makes people tick. Usually once he's found out, they don't tick anymore." WHERE name="Klaus";
UPDATE button SET flavor_text="Krosp is a failed experiment. This makes him cranky." WHERE name="Krosp";
UPDATE button SET flavor_text="Orgasm Lass is an X-rated Super Hero. She champions the power of sexual healing in her battle against villains, monsters and such. Occasionally that healing takes the form of S&M, and she gets to beat people up." WHERE name="O-Lass";
UPDATE button SET flavor_text="Von Pinn is ruthless, efficient and amoral. This makes her an excellent housekeeper." WHERE name="Von Pinn";
UPDATE button SET flavor_text="Angel repairs vintage motorcycles and enjoys picnics by moonlight. She is a staunch advocate of women's suffrage, and she likes to beat people up." WHERE name="Angel";
UPDATE button SET flavor_text="Buddy is a heartless brute without soul or conscience. It likes cabbages and howling, and it likes to beat people up." WHERE name="Buddy";
UPDATE button SET flavor_text="Dunkirk is a mysterious Balkan folk dancer. He often taunts his victims with hours of tuneless humming, and he likes to beat people up." WHERE name="Dunkirk";
UPDATE button SET flavor_text="Durban McGinty sleeps with one eye open and is easily startled when awake. He is never without something to chew on, and he likes to beat people up." WHERE name="McGinty";
UPDATE button SET flavor_text="Starchylde is a ferocious vampire hunter and a prolific poet. She likes garlic, mice and ultraviolet light, and she likes to beat people up." WHERE name="Starchylde";
UPDATE button SET flavor_text="Tiffany is a robotics expert and gourmet chef. Her travels often take her to remote locations in Tibet and Pakistan, and she likes to beat people up." WHERE name="Tiffany";
