UPDATE button SET flavor_text="\"Thick\" Tony DeLuca: Thick Tony prowls the moonlit streets of Fight City with a chip on his shoulder and an impossibly tiny pork pie on his head. He likes dinner theater, black coffee, stakeouts, and beating people up." WHERE name="Tony (The Core)";
UPDATE button SET flavor_text="Captain Stephen Send: \"Three-Fingered Steve\" actually has six fingers and two thumbs. He likes explosives, sharks, exploding sharks, and sharks that explode. And he likes to beat people up." WHERE name="Steve (The Core)";
UPDATE button SET flavor_text="David Ferrer: David \"Honey\" Ferrer is a cruel man with a stick and a gun. He enjoys the solace of a quiet evening with Schubert and Armagnac, the calming hum of a thousand bees, and beating people up." WHERE name="Ferrer";
UPDATE button SET flavor_text="Donna Chase: Donna is a hard-nosed, fast-talking stunt driver who smuggles exotic animals and unusual auto parts. She likes matchsticks, binturongs, and beating people up." WHERE name="Donna";
UPDATE button SET flavor_text="Hollis Henry: Hollis is a fatuous turncoat who would trade his pet rabbit for a warm pair of socks. He is never found within ten feet of the truth, and he likes to beat people up." WHERE name="Hollis";
UPDATE button SET flavor_text="Janet Rialto: In a jam? Call the law offices of Janet Rialto. No job too small. Most solutions safe and legal. Divorce, Custody, Injury, Wrongful Prosecution, Arson, Beating People Up." WHERE name="Janet";
UPDATE button SET flavor_text="Julian Smith: Julian \"Calendar\" Smith can spend a week in a blind. Julian likes taking out the garbage, elaborate disguises, learning intimate details of high-profile targets, and beating people up." WHERE name="Smith";
UPDATE button SET flavor_text="Mayor Delia Culvert: Delia \"La Rata\" Culvert is a ruthless taskmaster with a penchant for exotic cheeses. She likes earthworms, menthols, wielding power through a vast network of spies, and beating people up." WHERE name="Delia";
UPDATE button SET flavor_text="Polly Flowers: Polly is a strong-willed historical revisionist whose deepest regret is that she despises long walks on the beach. She likes ikebana, territorial collectives, and beating people up." WHERE name="Polly";
UPDATE button SET flavor_text="Porter Stratos: \"Downtown\" Porter Stratos is a small-minded killer who will do anything because he believes in nothing. He prefers argan oil to aloe, Hong Kong to Savile Row, and he likes to beat people up." WHERE name="Porter";
UPDATE button SET flavor_text="Stefano Serilio: Stefano is a meticulous obsessive who spends hours each morning separating beach sand into piles of different colors. He likes ink, a sense of purpose in the universe, and beating people up." WHERE name="Stefano";
UPDATE button SET flavor_text="Tanya Love: Tanya Love has an abiding love of firearms and wields power and status far higher than her tender age would suggest. She likes scrimshaw, herd animals, brewery mold, and beating people up." WHERE name="Tanya";
UPDATE button SET flavor_text="Hamilton Weeks: Charlie \"Hamilton\" Weeks is a deeply thoughtful and engaged human being whose delights in the simple things cannot be overestimated. He likes dodgeball, high-speed photography, and beating people up." WHERE name="Hamilton";
UPDATE button SET flavor_text="Emerita \"Lady B\" Brighton: Emerita Brighton is an eminent restaurateur and porcelain doll collector who lives in an unusually small apartment and likes literally everything, including beating people up." WHERE name="Lady B";
UPDATE button SET flavor_text="Wallace Weber: Wallace Weber is a beat cop in every sense. He likes robbing dead drops, hassling his boss for a raise, and beating people up." WHERE name="Wallace";

UPDATE button SET flavor_text="Ho Min-Szu: Ho Min-Szu is a talented car thief with a secret garage and a bright future. He services all makes and models, he always has the part you need, and he likes to beat people up." WHERE name="Min-Szu";
UPDATE button SET flavor_text="Keegan Howels: Keegan Howels is a meticulous floorman who often struggles to distinguish fantasy from reality. He collects exotic spices and avoids daylight at all costs, and he likes to beat people up." WHERE name="Keegan";
UPDATE button SET flavor_text="Jerry Corson: \"Waterline\" Jerry Corson is a water taxi pilot who inevitably breaks the ice with tales of his nefarious side projects. He collects doorknobs and decorative soaps, and he likes to beat people up." WHERE name="Jerry";
UPDATE button SET flavor_text="Gilroy Grimes: Gilroy is a drunken goofball who will cut you like a pack of cards. He likes the wee hours, cheating at pinochle, and beating people up." WHERE name="Gilroy";
UPDATE button SET flavor_text="Brand Golver: Brand Golver would rather spend his days on the links, but there is always someone who wants something done properly, and he is the man to do that. He likes fireflies, ceramic roof tiles, and beating people up." WHERE name="Brand";
UPDATE button SET flavor_text="Benvenito Buonasera: Benvenito Buonasera owns the Mighty Malt Club on Pelican Island. He will be onstage in five minutes, he is currently accepting requests, and he likes to beat people up." WHERE name="Benvenito";
UPDATE button SET flavor_text="\"Pilot\" Joe Cambry: \"Pilot\" Joe Cambry once had that Frank Sinatra in his cab. He is affable, moderately articulate, and possessed of myriad indefensible political opinions, and he likes to beat people up." WHERE name="Pilot Joe";
UPDATE button SET flavor_text="Szechuan Pierce: Szechuan Pierce is not as delicate as she looks, and she is so tired of your crap. She likes deals without hitches, getting along whenever practical, and beating people up." WHERE name="Szechuan";
UPDATE button SET flavor_text="Karen \"Lady K\" Wollerry: Karen \"Lady K\" Wollerry is even closer to the edge than she looks. She is fastidious, capricious, and unforgiving, and sleeps less than an hour a day. And she likes - no, loves - to beat people up." WHERE name="Lady K";
UPDATE button SET flavor_text="Jocasta Pierce-Wilson: Jocasta owns you and you don't even know it. She likes managing casinos, barbed wire, and the muffled snap of a professionally broken bone. And she likes to beat people up." WHERE name="Jocasta";
UPDATE button SET flavor_text="Fiorina Pierce: \"Pyramid Casino Group, please hold.\"" WHERE name="Fiorina";
UPDATE button SET flavor_text="Cerise Collins: Cerise is a deep-sea diver and licensed pulmonologist. She collects decorative erasers and once went for six months without sneezing, and she likes to beat people up." WHERE name="Cerise";
UPDATE button SET flavor_text="Doctor Fret: Doctor William J. Fret has a bag of tools that you do not want to see. He likes patience, surprises, and getting to the truth, and he likes to beat people up." WHERE name="Doctor Fret";
UPDATE button SET flavor_text="Felicia Honora: Felicia Honora believes in the immutable tenets of objectivist capitalism and can make ten million dollars disappear with a pencil. She likes whales, absolute silence, and beating people up." WHERE name="Felicia";
UPDATE button SET flavor_text="Windsor Castle: Windsor Castle can tell you the news before it happens. He has seen all this before, and he is frankly embarrassed that no one else saw this coming. He likes Bertrand Russell, moonglow on the Rio Vinareto, and beating people up." WHERE name="Windsor";

# "Backer" should have an umlaut on the 'a'
UPDATE button SET flavor_text="Sal Backer: Hansel \"California Sal\" Backer is an acolyte of Poseidon and a master of the sea. He earned his nickname by having no idea where he was or where he was going, and he likes to beat people up." WHERE name="Sal";
UPDATE button SET flavor_text="Marin Reed: Marin Fleet Reed is a precise and unforgiving employer who wastes countless hours negotiating for the slightest advantages. He enjoys staring contests, Wadjet, and beating people up." WHERE name="Marin";
UPDATE button SET flavor_text="Dietrich Weiss: Dietrich Weiss would like to see some identification. He has a black belt in a martial art of his own devising, which pretty much only works if you are over seven feet tall, and likes to beat people up." WHERE name="Dietrich";
UPDATE button SET flavor_text="Carson Bell: Carson Bell liked Water Town before it was all built up. Time was you could see Lee Point from the Kennerick Yards and everything north of Ather Street was just swampland. He likes hay, wine, and beating people up." WHERE name="Carson (West Side)";
UPDATE button SET flavor_text="Bijay Purinam: Bijay is a tavern owner and a strict constitutionalist. He enjoys teleology, Canadian porters, and table games with little or no strategy. And he likes to beat people up." WHERE name="Bijay";
UPDATE button SET flavor_text="Stacie Jones: Stacie \"Candy Pop\" Jones has one thousand absurd yet unfalsifiable theories. He likes surprises, ditching work, golf balls, and beating people up." WHERE name="Stacie";
UPDATE button SET flavor_text="Sally LaSombre: Sally LaSombre is an orphan from Corton City. She can strip a car into its component parts in fifteen minutes, and she accepts only cash. She likes disaster movies, anonymity, and fishing, and she likes to beat people up." WHERE name="Sally";
UPDATE button SET flavor_text="Prentice Reed: Prentice Reed takes some getting used to. She is not one to varnish her opinion, and will get into a fight about literally anything that comes out of your mouth. She likes Langton Ale, prisms, and beating people up." WHERE name="Prentice";
UPDATE button SET flavor_text="Marta Cosgrove: Marta Cosgrove will take the starch right out of that smart lip, young man. She is a steadfast advocate for the lifestyle of an independent woman, and she likes to beat people up." WHERE name="Marta";
UPDATE button SET flavor_text="Jackie Waters: Jackie is a respected charcutier and aerial tour guide. She likes mothballs, terrines, the soft caress of the cold winter sea, and beating people up." WHERE name="Jackie";
UPDATE button SET flavor_text="Hazel Tenant: Hazel Tenant keeps the wires from crossing at the West Side 504. She is a compulsive diarist whose annals log the secret history of the city. She likes gossip, the ring of fine porcelain, and beating people up." WHERE name="Hazel";
UPDATE button SET flavor_text="Beatrice Reed-Wheeler: Beatrice Reed-Wheeler has a radiant beauty that belies her advanced years. She is an accomplished campanologist and trauma surgeon, and she likes red grapes, old snapshots, and beating people up." WHERE name="Beatrice";
UPDATE button SET flavor_text="Rider Henry: Rider Henry once shot a 66 at Palatka and he never shuts up about it. He enjoys precision in all things, the Bugatti Type 23 Brescia Tourer, Inglenook Cab '41, and beating people up." WHERE name="Rider";
UPDATE button SET flavor_text="Edmondo Rivera: Do. Not. Push me." WHERE name="Mondo";
UPDATE button SET flavor_text="Mickael Mezzo: Mickael Mezzo is an imbecile who surfs an endless wave of his father's generosity and protection. He likes stacking up rocks, and that is pretty much it, aside from occasionally beating people up." WHERE name="Mickael";

UPDATE button SET flavor_text="Ricky Pietrasanta: Ricardo \"Ricky\" Pietrasanta runs a ship as tight as his necktie. He likes alibis, the recent string of unrelated kidnappings, multiple vacancies in municipal government, and beating people up." WHERE name="Ricky";
UPDATE button SET flavor_text="Petey Petri: No car engine in the world is running so well that Petey Petri can leave it alone. He likes visits to the zoo, knowing where his tools are, and beating people up." WHERE name="Petey";
UPDATE button SET flavor_text="Mississippi Max: \"Mississippi\" Max Storey is a former circus clown with an assassin's cold stare and a respectable .324. He hates thunderstorms and the sound of chewing, and he likes to beat people up." WHERE name="Mississippi (Uptown)";
# "Partagas" should have an acute accent on the last 'a'
UPDATE button SET flavor_text="Ken Ochoa: Ken Ochoa can buy and sell the people who could buy and sell you. He prefers Partagas Perfectos Finos, Le Corbusier, the Patek Gyromax, and beating people up." WHERE name="Ken (Uptown)";
UPDATE button SET flavor_text="Henry White: \"Pawtucket\" Henry White doesn't care who are you, where you came from, or how long you are staying. He also doesn't need your opinion on how to get there. Pretty much all he cares about is beating people up." WHERE name="Henry";
UPDATE button SET flavor_text="Giuseppe Stone: Giuseppe Stone can eat fifty eggs. He is a model citizen with several successful and well-respected legitimate businesses. He likes garlic, red wine, outliving his enemies, and beating people up." WHERE name="Giuseppe";
UPDATE button SET flavor_text="Clyde Fischer: Harold \"Clyde\" Fischer is a monstrous horse trainer with a short temper and a big gun. His every adult decision has been the result of a preadolescent misconception, and he likes to beat people up." WHERE name="Clyde";
UPDATE button SET flavor_text="Basil Tyron: Basil \"The Basilisk\" Tyron can think of about a hundred places he would rather be right now. He likes doing things the easy way, working this out like adults, and beating people up." WHERE name="Basil";
# "Perez" should have an acute accent on the first 'e'
UPDATE button SET flavor_text="Montserrat Perez: Montserrat Perez is a calculating hustler who wants to know if you'd like to make this interesting. She likes nine-ball, humidity, the idea of clowns, and beating people up." WHERE name="Montserrat";
UPDATE button SET flavor_text="Jesse Millions: Jesse Millions can lift a car. She knows where the bodies are buried, and she knows who buried them. She likes mice, cats, and sea urchins, all for different reasons, and she likes to beat people up." WHERE name="Jesse";
UPDATE button SET flavor_text="Heather Gwinn: Heather Dobro Gwinn takes no pleasure in what she is about to do to you. She likes screenwriting, steel mills, and a team of well-trained bodyguards. And she likes to beat people up." WHERE name="Heather (Uptown)";
UPDATE button SET flavor_text="Amelia Farnese: Amelia Farnese can listen to every conversation in the room. She likes leaping, the sour taste of envelope glue, and the sound of distant church bells. And she likes to beat people up." WHERE name="Amelia";
UPDATE button SET flavor_text="Bobby McGinn: \"Texas\" Bobby McGinn knows every hoodlum on the streets of Leriston, Providence, and Shepherd City. He likes carnauba wax, a strong handshake, and watching things burn, and he likes to beat people up. " WHERE name="Bobby";
UPDATE button SET flavor_text="Tasha Rudenko: Natasha Rudenko is a wicked sorceress sent from another world to bark strange commands and to withhold delicious treats. She likes it when no one gets bitten, and she likes to beat people up." WHERE name="Tasha";
UPDATE button SET flavor_text="Johnny Stubbs: When Johnny Stubbs mentions \"the cigar trick,\" you should change the subject quickly but carefully. He likes gritty tales of wrongdoing, birdsong at first light, and beating people up." WHERE name="Stubbs";
