UPDATE button SET tourn_legal = 0
WHERE
  name = 'Max' OR
  name = 'Agent Orange' OR
  name = 'Huitzilopochtli' OR
  name = 'Lisa' OR
  name = 'Nethershadow' OR
  name = 'Phuong' OR
  name = 'Uncle Scratchy' OR
  name = 'Al-Khwarizmi' OR
  name = 'Carl Friedrich Gauss' OR
  name = 'Fan Chung Graham' OR
  name = 'Ron Graham' OR
  name = 'Leonard Eugene Dickson' OR
  name = 'Paul Erdos' OR
  name = 'Pythagoras' OR
  name = 'Theano' OR
  name = 'Apples' OR
  name = 'Green Apple' OR
  name = 'Buck' OR
  name = 'Cass' OR
  name = 'Crysis' OR
  name = 'Golo' OR
  name = 'Z-Don' OR
  name = 'Carson (promo)' OR
  name = 'Daisy' OR
  name = 'Jingjing' OR
  name = 'Mau' OR
  name = 'Spencer' OR
  name = 'Talus' OR
  name = 'Angora' OR
  name = 'Amara Wintersword' OR
  name = 'Captain Bingo' OR
  name = 'Oni' OR
  name = 'Spite' OR
  name = 'Super Germ' OR
  name = 'Dr. Speculo' OR
  name = 'Harry Pudding' OR
  name = 'MothMan' OR
  name = 'Assailer' OR
  name = 'Harbinger' OR
  name = 'ConMan' OR
  name = 'Pikathulhu' OR
  name = 'Ulthar';

UPDATE button SET tourn_legal = 1
WHERE
  name = 'Dead Guy';
