INSERT INTO buttonset (id, name, sort_order) VALUES
(83, 'Peloton', 7700);

INSERT INTO button (id, name, recipe, btn_special, tourn_legal, set_id) VALUES
(778, 'Floriano',        'n(4) f(8) s(10) z(20) (X)',                      0, 0, (SELECT id FROM buttonset WHERE name="Peloton")),
(779, 'Roger',           'd(4) H(8) g(10) G(10) (X)',                      0, 0, (SELECT id FROM buttonset WHERE name="Peloton")),
(780, 'Doyle',           'k(4) ^(8) M(10) o(20) (X)',                      0, 0, (SELECT id FROM buttonset WHERE name="Peloton")),
(781, 'Julia',           'p(4) t(8) b(10) B(20) (X)',                      0, 0, (SELECT id FROM buttonset WHERE name="Peloton")),
(782, 'Mariusz',         'm(4) G(8) q(10) M(10) (X)',                      0, 0, (SELECT id FROM buttonset WHERE name="Peloton")),
(783, 'Antonio',         'c(4) f(8) %(10) h(10) (X)',                      0, 0, (SELECT id FROM buttonset WHERE name="Peloton")),
(784, 'Orlando',         's(4) ^(8) g(10) I(10) (X)',                      0, 0, (SELECT id FROM buttonset WHERE name="Peloton")),
(785, 'Timea',           'q(4) M(8) d(10) z(10) (X)',                      0, 0, (SELECT id FROM buttonset WHERE name="Peloton"));

UPDATE button SET flavor_text="Sprinters ride hidden in the peloton for the whole race (shadow) and in the final meters they pick the right moment (focus) to jump ahead and use their speed (speed) to win the race. However if the race profile is not flat and has some climbs, they are helpless and never win such races (null)." WHERE name="Floriano";
UPDATE button SET flavor_text="Climbers are very strong riders (mighty), can attack and counter attack multiple times (rage), and can also judge their pace depending on the difficulty of the climb in order not to use up all their energy too soon (stinger). They are also skilled (stealth) downhillers." WHERE name="Roger";
UPDATE button SET flavor_text="Time trialers (time&space) can keep a constant (konstant) high pace (maximum) over a certain period of time, usually around one hour. They ride alone on the course and have no team to help them, so a lot depends on whether they are having a good or bad day (ornery)." WHERE name="Doyle";
UPDATE button SET flavor_text="Puncher is an explosive type of rider (boom). Punchers can quickly accelerate, but can't keep up a high tempo for too long (berserk). They usually make surprise attacks on small hills or when other riders are suffering (poison). They have good stamina and ride well on cobbles, where others slow down to avoid a fall (trip)." WHERE name="Julia";
UPDATE button SET flavor_text="Domestiques are the main helpers for the team captain. They are strong climbers (rage), they need to adjust their pace to the captain's pace (morphing) and give the captain maximum help (maximum) on the climbs. They ride at the front but they move back into the shade of the peloton in the closing stages of the race (queer)." WHERE name="Mariusz";
UPDATE button SET flavor_text="Break away riders are always the first to attack (focus) and do so right from the start. Their intention is to split from the main group (radioactive) and ride alone hoping the peloton never catches them. But as they ride alone at the front, they expend a lot of energy and their pace slowly decreases (weak). Sometimes the peloton increases its pace too late to catch the break and this is (chance) what those riders are hoping for." WHERE name="Antonio";
UPDATE button SET flavor_text="Allrounder is usually the rider who wins big tours. Allrounders are usually a mix of a climber (stinger die from the climber rider) and time trialer (time&space die from time trialer rider). Allrounders are often protected, following the wheel of a team mate (shadow). They are usually given the role of captain and would not agree to take any other role in the team (insult)." WHERE name="Orlando";
UPDATE button SET flavor_text="Lead out is usually a sprinter (speed) who is a bit less athletically built than the pure sprinters are, thus being a bit slower, but performing better on lumpy stages. On a flat course the lead out would serve as the domestique for the main sprinter and would lead the sprinter out to the final finish in the last kilometer (maximum and queer skills from domestique). However on the stages which require more climbing, such riders would perform better than pure sprinters who usually drop behind the pack. Lead out riders could win a stage because they are faster and more skilled (speed, stealth) than the rest of the riders arriving together at the finish line." WHERE name="Timea";
