INSERT INTO buttonset (id, name, sort_order) VALUES
(89,  '2010 Rare / Promo', 8900),
(90,  'Tributes',          9000),
(91,  'Standard Action',   9100),
(92,  'Button Ponies',     9200),
(93,  'Scott Pilgrim',     9300),
(94,  'Cryptonom',         9400);

INSERT INTO button (id, name, recipe, btn_special, tourn_legal, set_id) VALUES
(837,  'Julz',         '(4) (4) (8) (12) z(20)',        0, 0, (SELECT id FROM buttonset WHERE name="2000 Rare / Promo")),
(838,  'Eberk',        '(2) (3) (6) (7) (10/16)',       0, 0, (SELECT id FROM buttonset WHERE name="2010 Rare / Promo")),
(839,  'Bunny Temple', '(5) (5) (5) (5) (V)',           0, 0, (SELECT id FROM buttonset WHERE name="Tributes")),
(840,  'Bernie',       'D(4) (20) (4/8) (6/8) D(S)',    0, 0, (SELECT id FROM buttonset WHERE name="Free Radicals")),
(841,  'GG',           '(6) (6) D(12) D(24) (S)',       0, 0, (SELECT id FROM buttonset WHERE name="Free Radicals")),
(842,  'Wumpus',       '(4) (8) (8) (X) (X)',           0, 1, (SELECT id FROM buttonset WHERE name="Sanctum")),
(843,  'Edda',         '(4) (8) (10) (16) (X)',         0, 1, (SELECT id FROM buttonset WHERE name="Standard Action")),
(844,  'Fernando',     '(6) (12) (12) (20) (X)',        0, 1, (SELECT id FROM buttonset WHERE name="Standard Action")),
(845,  'Applejack',    'p(6) p(10) g(12) (20) (X)',     0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(846,  'Chrysalis',    'm(4) m(6) m(8) m(10) m(12)',    0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(847,  'Fluttershy',   '(6) G(8) =(10) (X) (X)',        0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(848,  'Pinkie Pie',   '(4) z(6) (12) o(20) q(X)',      0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(849,  'Rainbow Dash', '(8) z(8) z(10) sp(20) (X)',     0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(850,  'Rarity',       '(4) I(8) I(8) o(12) (X)',       0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(851,  'Twilight Sparkle', '(4) G(8)  F(10) T(12) (X)', 0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(852,  'Changeling (BP)', '(X) (X) (X) (X) (X)',        0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(853,  'Angel (BP)',    '(1) (1) (1) (1) (X)',          0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(854,  'Parasprites',   '(2) (2) (2) (2) (X)',          0, 0, (SELECT id FROM buttonset WHERE name="Button Ponies")),
(855,  'Envy Adams',     '(6) (10) (12) (20) (X)',      0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(856,  'Final Form GGG', '(20) (20) (20) (X) (X)',      0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(857,  'Gideon G Graves','(4) (6) (10) (X) (X)',        0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(858,  'Lucas Lee',      '(6) (10) (12) (20) (X)',      0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(859,  'Matthew Patel',  '(4) (4) (10) (10) (X)',       0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(860,  'Nega Scott',     '(4) (8) (10) (20) (X)',       0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(861,  'Ramona Flowers', '(4) (8) (8) (10) (X)',        0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(862,  'Scott Pilgrim',  '(4) (10) (12) (12) (X)',      0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(863,  'Roxy Richter',   '(6) (8) (10) (20) (X)',       0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(864,  'Todd Ingram',    '(8) (10) (10) (20) (X)',      0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(865,  'Katayanagi Twins', '(10) (10) (10) (10) (X)',   0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(866,  'Knives Chau',    '(4) (6) (12) (12) (X)',       0, 0, (SELECT id FROM buttonset WHERE name="Scott Pilgrim")),
(867,  'Enjileon',       'Hv(2,2) v(R)! v(T,T)? vp(X,X)',0,0, (SELECT id FROM buttonset WHERE name="Cryptonom"));
