#!/usr/bin/python
#####
# Utility to migrate decline_auxiliary action log entries to new format
#
# N.B. decline_auxiliary does not actually have any parameters, so
# there is no secondary table; we just clear the now-extraneous message
# from the existing table

import json
import MySQLdb

def migrate_to_type_log_decline_auxiliary(row, crs):
  row_id = row[0]
  update_sql = 'UPDATE game_action_log SET message=NULL WHERE id=%d' % (row_id)
  result = crs.execute(update_sql)
  if not result == 1:
    raise ValueError, "Got unexpected return %s from %s" % (result, update_sql)
  print "Deleted row %s message %s from game_action_log" % (row[0], row[1])

conn = MySQLdb.connect(user='root', db='buttonmen')
crs = conn.cursor()
results = crs.execute(
  'SELECT id,message FROM game_action_log WHERE action_type="decline_auxiliary" ' + \
  'AND message IS NOT NULL')
if results > 0:
  for row in crs.fetchall():
    migrate_to_type_log_decline_auxiliary(row, crs)
conn.commit()
