#!/usr/bin/python
#####
# Utility to migrate end_draw action log entries to new format

import json
import re
import MySQLdb

END_DRAW_OLD_STRING_RE = re.compile('^Round (\d+) ended in a draw \((-?\d+(?:\.\d+)?) vs\. (-?\d+(?:\.\d+)?)\)$')

def get_last_insert_id(crs):
  crs.execute('SELECT LAST_INSERT_ID()')
  return crs.fetchone()[0]

def migrate_to_type_log_end_draw(row, crs):
  row_id = row[0]
  try:
    msgdata = json.loads(row[1])
    round_number = msgdata['roundNumber']
    assert(len(msgdata['roundScoreArray']) == 2)
    assert(msgdata['roundScoreArray'][0] == msgdata['roundScoreArray'][1])
    round_score = msgdata['roundScoreArray'][0]
  except ValueError:
    mobj = END_DRAW_OLD_STRING_RE.match(row[1])
    if not mobj:
      raise ValueError, "Could not match string: %s" % row[1]
    round_number = mobj.group(1)
    assert(mobj.group(2) == mobj.group(3))
    round_score = mobj.group(2)
  insert_sql = 'INSERT INTO game_action_log_type_end_draw ' + \
    '(id, round_number, round_score) VALUES ' + \
    '(0, %s, %s);' % (round_number, round_score)
  result = crs.execute(insert_sql)
  if not result == 1:
    raise ValueError, "Got unexpected return %s from %s" % (result, insert_sql)
  type_log_id = get_last_insert_id(crs)
  update_sql = 'UPDATE game_action_log SET type_log_id=%s,message=NULL WHERE id=%d' % (type_log_id, row_id)
  result = crs.execute(update_sql)
  if not result == 1:
    raise ValueError, "Got unexpected return %s from %s" % (result, update_sql)
  print "Moved %s to game_action_log_type_end_draw id %s" % (row[1], type_log_id)

conn = MySQLdb.connect(user='root', db='buttonmen')
crs = conn.cursor()
results = crs.execute(
  'SELECT id,message FROM game_action_log WHERE action_type="end_draw" ' + \
  'AND type_log_id IS NULL')
if results > 0:
  for row in crs.fetchall():
    migrate_to_type_log_end_draw(row, crs)
conn.commit()
