#!/usr/bin/env python

##### head-to-head.py
#
# Show head-to-head records between a protagonist (a button or a player)
# and one or more opponents.

### Imports

# Import stuff from the future.

from __future__ import absolute_import, division, print_function, unicode_literals

# Import regular stuff.

import argparse
import os
import sys

# Import Python version specific stuff.

try:
  import configparser
except ImportError:
  import ConfigParser as configparser

# Import Button Men utilities.

sys.path.append('lib')
import bmutils

### Functions

## parse_arguments

def parse_arguments():

  # Set up the main parser and subparser.

  parser = argparse.ArgumentParser(description="Show head-to-head records between a protagonist (a button or a player) and one or more opponents.")

  subparsers = parser.add_subparsers(dest='type', title="Type of thing to compare",
                                     help="more help: head-to-head <subcommand> --help")

  # Set up the button subparser.

  parser_button = subparsers.add_parser('button', help="show head-to-head records between buttons")

  parser_button.add_argument('protag', help="protagonist button")

  parser_button.add_argument('opponent',
                             nargs = '+',
                             help = "opponent buttons")

  # Set up the player subparser.

  parser_player = subparsers.add_parser('player', help="show head-to-head records between players")

  parser_player.add_argument('protag', help="protagonist player")

  parser_player.add_argument('opponent',
                             nargs = '+',
                             help = "opponent players")

  # Add general optional arguments.

  parser.add_argument('--n-way',
                      action='store_true',
                      help = "compare opponents to each other as well")

  parser.add_argument('--site',
                      default = 'www',
                      help = "site to check ('www' by default)")

  parser.add_argument('--config', '-c',
                      default='~/.bmrc',
                      help="config file containing site parameters")

  # Return the parser.

  return parser.parse_args()
          
## print_record
#
# Print the record between two things.

def print_record(bmconn, type, thing1, thing2):

  apicmd = { 'type': 'searchGameHistory',
             'sortColumn': 'lastMove',
             'sortDirection': 'DESC',
             'numberOfResults': 20,
             'page': 1,
             type + 'NameA': thing1,
             type + 'NameB': thing2,
             'status': 'COMPLETE' }

  result = bmconn._make_request(apicmd)

  # If we don't get an ok result, print some helpful info, and give up.

  if result.status != 'ok':
    print("WARNING: Couldn't get data about {0} vs {1}".format(thing1,thing2))
    print("Result status: {0}".format(result.status))
    print("Result message: {0}\n".format(result.message))
    return

  # If we're still here, set some variables, figure out the win
  # percentage, and print the answer.

  wins = result.data['summary']['gamesWonA']
  losses = result.data['summary']['gamesWonB']
  games = result.data['summary']['gamesCompleted']

  try:
    winpct = (wins / games) * 100
  except ZeroDivisionError:
    winpct = 0

  print("{0} vs {1}: {2} - {3} ({4:.2f}%)".format(thing1, thing2, wins, losses, winpct))

### Main body

args = parse_arguments()

# Connect to the site.

try:
  bmconn = bmutils.BMClientParser(os.path.expanduser(args.config), args.site)
except configparser.NoSectionError as e:
  print("ERROR: {0} doesn't seem to have a '{1}' section".format(args.config, args.site))
  print("(Exception: {0}: {1})".format(e.__module__, e.message))
  sys.exit(1)

if not bmconn.verify_login():
  print("ERROR: Could not log in to {0}".format(args.site))
  sys.exit(1)

# Get head-to-head info between the main protagonist and each of the
# opponents.

for opponent in args.opponent:
  print_record(bmconn, args.type, args.protag, opponent)

# If we're doing an n-way comparison, compare the other pairs too.

if args.n_way:
  opponents = args.opponent
  for protag in args.opponent:
    opponents = opponents[1:]
    for opponent in opponents:
      print_record(bmconn, args.type, protag, opponent)
