#!/usr/bin/env python
# MONITOR
# Example script which provides "monitor" functionality, polling
# periodically for games which are waiting for you to act


import argparse
import sys
import time
from builtins import input

from lib import bmutils


# implicitly parses sys.argv
def parse_args():
  parser = argparse.ArgumentParser()
  parser.add_argument(
    "-c", "--config",
    help="config file containing site parameters",
    type=str, default=".bmrc"
  )
  parser.add_argument(
    "-s", "--site",
    help="buttonmen site to access",
    type=str, default="www"
  )
  return parser.parse_args()


args = parse_args()

b = bmutils.BMClientParser(args.config, args.site)
if not b.verify_login():
  print("Could not login")
  sys.exit(1)

while True:
  games = b.wrap_load_active_games()
  games_active = False
  for game in games:
    if game['isAwaitingAction']:
      print("%s: %s (%s) vs. %s (%s)" % (
        game['gameId'], b.username, game['myButtonName'],
        game['opponentName'], game['opponentButtonName']))
      games_active = True
  if games_active:
    confirm = input()
  else:
    time.sleep(30)
