#!/usr/bin/env python

##### record.py
#
# Show overall record of one or more buttons or players.

### Imports

# Import stuff from the future.

from __future__ import division

# Import regular stuff.

import ConfigParser
import argparse
import os
import sys

# Import Button Men utilities.

sys.path.append('lib')
import bmutils

### Functions

## parse_arguments

def parse_arguments():

  # Set up the main parser and subparser.

  parser = argparse.ArgumentParser(description="Show overall record of one or more buttons or players.")

  subparsers = parser.add_subparsers(dest='type', title="Type of thing to show",
                                     help="more help: record <subcommand> --help")

  # Set up the button subparser.

  parser_button = subparsers.add_parser('button', help="show button record(s)")

  parser_button.add_argument('names',
                             nargs = '+',
                             help="button(s) to show ('all' for all buttons)")

  # Set up the player subparser.

  parser_player = subparsers.add_parser('player', help="show player record(s)")

  parser_player.add_argument('names',
                             nargs = '+',
                             help="player(s) to show ('all' for all players)")

  # Add general optional arguments.

  parser.add_argument('--config', '-c',
                      default='~/.bmrc',
                      help="config file containing site parameters")

  parser.add_argument('--site',
                      default = 'www',
                      help = "site to check ('www' by default)")

  # Return the parser.

  return parser.parse_args()
          
## print_record
#
# Print the overall record of a thing.

def print_record(bmconn, type, thing):

  apicmd = { 'type': 'searchGameHistory',
             'sortColumn': 'lastMove',
             'sortDirection': 'DESC',
             'numberOfResults': 20,
             'page': 1,
             type + 'NameA': thing,
             'status': 'COMPLETE' }

  result = bmconn._make_request(apicmd)

  # If we don't get an ok result, print some helpful info, and give up.

  if result.status != 'ok':
    print "WARNING: Couldn't get data about {0}".format(thing)
    print "Result status: {0}".format(result.status)
    print "Result message: {0}\n".format(result.message)
    return

  # If we're still here, set some variables, figure out the win
  # percentage, and print the answer.

  wins = result.data['summary']['gamesWonA']
  losses = result.data['summary']['gamesWonB']
  games = result.data['summary']['gamesCompleted']

  try:
    winpct = (wins / games) * 100
  except ZeroDivisionError:
    winpct = 0

  print "{0} overall record: {1} - {2} ({3:.2f}%)".format(thing, wins, losses, winpct)

### Main body

args = parse_arguments()

# Connect to the site.

try:
  bmconn = bmutils.BMClientParser(os.path.expanduser(args.config), args.site)
except ConfigParser.NoSectionError as e:
  print "ERROR: {0} doesn't seem to have a '{1}' section".format(args.config, args.site)
  print "(Exception: {0}: {1})".format(e.__module__, e.message)
  sys.exit(1)

if not bmconn.verify_login():
  print "ERROR: Could not log in to {0}".format(args.site)
  sys.exit(1)

# If the name is 'all', do all the things.

if args.names == ['all']:

  # Prompt for confirmation first.

  print "WARNING: Getting records for all {}s will take a while and slow down the site. Are you sure?".format(args.type)
  confirm = raw_input("Type 'yes, really' to continue, anything else to abort: ")
  if confirm != "yes, really":
    print "You typed \"{}\", aborting now.".format(confirm)
    sys.exit(5)
  
  # If we're still here, get all the things.

  if args.type == 'button':
    names = bmconn.wrap_load_button_names()
  elif args.type == 'player':
    names = bmconn.wrap_load_player_names()
  else:
    print "ERROR: I don't know how print all things of this type ({})".format(args.type)
    sys.exit(1)

# Otherwise, just do the specified things.

else:

  names = args.names

# Print the overall record of the things.

for name in names:
  print_record (bmconn, args.type, name)
