# this workflow does not technically seem to be running at the moment
# the idea is that if your project accepts PRs from other peoples forks
# and you want their PR from their fork to run your GH Actions
# there can be some permissions issues around publishing test results onto the GHAction run
# and if you have the report publishing in a separate workflow some of that is mitigated
# FOR more info see:
# https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
# https://github.com/marketplace/actions/publish-unit-test-results#support-fork-repositories-and-dependabot-branches
# https://github.com/marketplace/actions/test-reporter#recommended-setup-for-public-repositories

# I DO NOT THINK THIS FILE IS REALLY USEFUL UNTIL ITS ON THE MASTER BRANCH

name: 'Test Report'
on:
  workflow_run:
    workflows: ['Button Men CI']                     
    types:
      - completed
permissions: {}

jobs:
  test-report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write
      # needed unless run with comment_mode: off
      pull-requests: write
      # only needed for private repository
      contents: read
      # only needed for private repository
      issues: read
      # required by download step to access artifacts API
      actions: read
    steps:

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: build_files

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          junit_files: './logs/*.xml'


    # another test publisher i was playing with
    # - name: DORNY LOCAL WORKFLOW
    #   uses: dorny/test-reporter@v1
    #   with:
    #     # artifact: build_files
    #     name: Some Tests
    #     path: './build/logs/*.xml'
    #     reporter: jest-junit